on:
  push:
    branches:
      - production

name: ğŸš€ Deploy production
concurrency: push_production

permissions:
  contents: write

env:
  CI: true

jobs:
  build-format-lint-test:
    name: ğŸš€ Build, lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: "âš™ï¸ğŸ“¦ï¸ Install & cache node dependencies"
        uses: ./.github/actions/install-node-deps
      - name: "âš™ï¸ğŸ› ï¸ Build"
        run: yarn build
      - name: "ğŸ§ªğŸ–¼ï¸ Test linter"
        run: yarn test:lint
      - name: "ğŸ§ªğŸ”¬ Run unit tests"
        run: yarn test:unit

  deploy:
    name: ğŸš€ Deploy production
    needs: build-format-lint-test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: "âš™ï¸ğŸ“¦ï¸ Install & cache node dependencies"
        uses: ./.github/actions/install-node-deps
      - name: "âš™ï¸ğŸ“œ Setup git config"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-pages-deploy-action@users.noreply.github.com"
      - name: ğŸš€ Deploy production
        run: yarn deploy
